### PR TITLE
threat model & risk assessment for k8s high availability demo

### PR DESCRIPTION
**Pull request by jgorczynski**
Create a threat model for our project. Resources to base this on:

- https://github.com/OWASP/threat-dragon - modeling tool used to create threat model diagrams by OWASP
- https://github.com/izar/pytm - yet another threat model tool, but Python-flavoured
- https://github.com/hysnsec/awesome-threat-modelling - something I usually start research from, namely awesome- framework. I.e. a list of selected links, references, etc.
- https://learn.microsoft.com/en-us/azure/security/develop/threat-modeling-tool - I'm also throwing in MS-based tool, in case e.g. it's more compatible with what we'd use in some other area. Although it most likely is vendor agnostic
- https://owasp.org/www-community/Threat_Modeling - overview of threat modeling and risk assessment from OWASP
- https://owasp.org/www-community/Threat_Modeling_Process#stride - STRIDE (threat categorization)
- https://www.practical-devsecops.com/dread-threat-modeling/ - DREAD (risk assessment)

**Don't stress any particular tool or approach here**, mostly because there is a mix of links destined for different purposes, i.e. some for threat modeling and some for risk assessment. 

Try to come up with something generic based on the requirements themselves; need to dive a little deeper to find out e.g. whether threat modeling/risk assessment requires some insight into business logic.

### CODE REVIEW

**Comment by MA3CIN** [comment]
@jgorczynski  We only do this for K8s, right? Not for compose nor for local development. Either way - I think i will only have a second to dive into this at Friday. If you want to progress with this task earlier, go ahead

**Comment by jgorczynski** [comment]
> @jgorczynski We only do this for K8s, right? Not for compose nor for local development. Either way - I think i will only have a second to dive into this at Friday. If you want to progress with this task earlier, go ahead

That's the thing here - actually the scope was not defined in the requirements at all ("risk analysis with threat model of the service"), therefore I want to devote some time to think how to approach this. Having other things on the plate, no earlier than Friday suits me as well

**Comment by MA3CIN** [comment]
@jgorczynski Fine with me - feel free to message me when you have time, as i suspect i will not be the first one to think this through :)

**Comment by jgorczynski** [comment]
Reassigning this just to me - as agreed earlier today on the call

**Comment by jgorczynski** [comment]
Yet another chunk of resources to follow:

- https://www.threatmodelingmanifesto.org/

> When you perform threat modeling, you begin to recognize what can go wrong in a system. It also allows you to pinpoint design and implementation issues that require mitigation, whether it is early in or throughout the lifetime of the system. The output of the threat model, which are known as threats, informs decisions that you might make in subsequent design, development, testing, and post-deployment phases.

- https://cheatsheetseries.owasp.org/cheatsheets/Threat_Modeling_Cheat_Sheet.html

> Threat modeling is ideally performed early in the SDLC, such as during the design phase. Moreover, it is not something that is performed once and never again. A threat model is something that should be maintained, updated and refined alongside the system. Ideally, threat modeling should be integrated seamlessly into a team's normal SDLC process; it should be treated as standard and necessary step in the process, not an add-on.

- https://www.techtarget.com/searchsecurity/tip/Risk-assessment-vs-threat-modeling-Whats-the-difference
> Risk assessments versus threat modeling is not an either/or. They play complementary roles

**Comment by jgorczynski** [comment]
@MA3CIN maybe this will be a valuable input to gather from Monday meeting in context of threat modeling - **Q: Is there any specific, preferred approach or method (like STRIDE or DREAD, recommended by OWASP) that you'd like us to follow?** 

My understanding is that threat modeling + risk analysis should be prepared for this application as a whole, not a particular microservice. But from this generic bullet point I lack an understanding of **what is expected in the end, by what standard/methodology etc.**

As you can see from my previous comments any other question I might ask while working on this will be a matter of asking you or other developers, as it revolves around design of the application and actually will be built upon it.

**Comment by MA3CIN** [comment]
@jgorczynski  Okay - i added the question to the doc. I will also show that we leverage SNYK on the Monday meeting

**Comment by jgorczynski** [comment]
**TODO** (based on notes from today's meeting):
- follow STRIDE method in order to come up with the threat model. **OWASP Threat Dragon** supports STRIDE natively - "provides modeling diagrams and implements a rule engine to auto-generate threats and their mitigations", being a nice rationale to use this [tool](https://github.com/OWASP/threat-dragon).
- start producing and collecting artifacts (diagrams, enumeration of threats and mitigations - as it will be a part of final documentation)

**Comment by jgorczynski** [comment]
**Current status:** Unfortunately I did not have much time lately to provide progress for this PR, but there will be some draft threat model **by the end of the week.**

**Comment by jgorczynski** [comment]
image

This is a quite simple version of diagram that we have at the moment - need to switch to web-based environment (OWASP Threat Dragon), apparently desktop version only allows to draw a diagram but STRIDE-compliant verifier/validation module is missing - at least for the macOS.

**Comment by MA3CIN** [comment]
Probably need to go more in-depth than just "Azure Cloud Application" - should probably be a set of boxes composed of (among others) - AKS LoadBalancer, Azure VNET, etc, etc. I suggest we synchronize at an evening soon, and instead focus on OAuth for now, because OAuth will influence our architecture and change the supposed attack vectors

**Comment by jgorczynski** [comment]
> Probably need to go more in-depth than just "Azure Cloud Application" - should probably be a set of boxes composed of (among others) - AKS LoadBalancer, Azure VNET, etc, etc. I suggest we synchronize at an evening soon, and instead focus on OAuth for now, because OAuth will influence our architecture and change the supposed attack vectors

I actually assumed (for now) a simplified view where arch is reduced to _Azure Cloud Application_ or a _web server_, because as long as very specific attack vectors affecting specific components (e.g. load balancer) are not considered - there is no need for it. But obviously there is a more detailed view to be modeled - of which I remember and sure, making progress in OAuth is one of the steps to push it.

**Regarding OAuth** - sure, we can sync soon. Wednesday works for me at the earliest.

**Comment by jgorczynski** [comment]
I am taking advantage of our postponed milestone deadline - this is the current, although still somewhat simplified, development of our threat model. I am appending consecutive threats, like this:

image

Once the threat model is finished we can easily have it documented, I think it would be the best way to e.g. choose some subset of threats, give a short description and mitigations, like here:

image

naturally it can be more detailed, this is merely an example of how can we approach this for the presentation.

**Comment by jgorczynski** [comment]
image

draft of the extended model; this looks somewhat final as we don't leverage `OAuth` or RBAC yet

**Comment by MA3CIN** [comment]
Nice! Well done :)

**Pull request merged**
