### PR TITLE
Update DBs schemas

### PR DESCRIPTION
**Pull request by WasilewM**
Changes:
- Add "name" column to Registered_Devices table

### CODE REVIEW

**Comment by MA3CIN** [comment]
I'm fine with this. Final call on the review should be made by @ASypula

**Comment by ASypula** [comment]
Good for me, as also talked with Mateusz, for now we will keep the "init scripts" for databases under appropriate folders with services as was initially setup by Marcin I think. And there will be one script with both schema and sample data but maybe in the future we could think of separating those 2.

**Comment by WasilewM** [comment]
> Good for me, as also talked with Mateusz, for now we will keep the "init scripts" for databases under appropriate folders with services as was initially setup by Marcin I think. And there will be one script with both schema and sample data but maybe in the future we could think of separating those 2.

**Comment by WasilewM** [comment]
> Good for me, as also talked with Mateusz, for now we will keep the "init scripts" for databases under appropriate folders with services as was initially setup by Marcin I think. And there will be one script with both schema and sample data but maybe in the future we could think of separating those 2.

We can also only keep the SQL scripts in init files for the services and in `database` directory only keep ERD images

**Pull request merged**
